INSERT INTO users (first_name, last_name, email, user_password)
VALUES ('John', 'Doe', 'test@test.com', '123');

INSERT INTO cooking_tools (tool_name)
VALUES ('Slow Cooker'), ('BBQ'), ('Smoker'), ('Pressure Cooker'), ('Stove Top'), ('Wok'), ('Rice cooker'), ('Sous vide'), ('Oven');


INSERT INTO ingredients (ingredient_name, category, subcategory)
VALUES 

-- protein poultry
('Chicken wings', 'protein', 'poultry'),
('Chicken drumsticks', 'protein', 'poultry'),
('Whole chicken', 'protein', 'poultry'),
('Spatch chicken', 'protein', 'poultry'),
('Chicken breast', 'protein', 'poultry'),
('Chicken thighs', 'protein', 'poultry'),
('Chicken leg', 'protein', 'poultry'),
('Ground chicken', 'protein', 'poultry'),
('Chicken tenders', 'protein', 'poultry'),
('Chicken wings', 'protein', 'poultry'),
('Chicken nuggets', 'protein', 'poultry'),
('Chicken sausage', 'protein', 'poultry'),
('Chicken liver', 'protein', 'poultry'),

-- protein beef
('Beef steak', 'protein', 'beef'),
('Beef roast', 'protein', 'beef'),
('Ground beef', 'protein', 'beef'),
('Beef ribs', 'protein', 'beef'),
('Beef shoulder', 'protein', 'beef'),
('Ribeye', 'protein', 'beef'),
('Burger patty', 'protein', 'beef'),
('Beef shank', 'protein', 'beef'),
('Beef brisket', 'protein', 'beef'),
('Beef tenderloin', 'protein', 'beef'),
('Flank steak', 'protein', 'beef'),
('Sirloin steak', 'protein', 'beef'),
('Top round steak', 'protein', 'beef'),
('Bottom round roast', 'protein', 'beef'),
('Chuck roast', 'protein', 'beef'),
('Short ribs', 'protein', 'beef'),

-- protein pork
('Pork chops', 'protein', 'pork'),
('Ground Pork', 'protein', 'pork'),
('Bacon', 'protein', 'pork'),
('Hotdog', 'protein', 'pork'),
('Pork loin', 'protein', 'pork'),
('Pork fillet', 'protein', 'pork'),
('Pepperoni', 'protein', 'pork'),
('Chorizo', 'protein', 'pork'),
('Pancetta', 'protein', 'pork'),
('Italian sausage', 'protein', 'pork'),
('Pork ribs', 'protein', 'pork'),

-- protein seafood
('Mussel', 'protein', 'seafood'),
('Scallop', 'protein', 'seafood'),
('Crab', 'protein', 'seafood'),
('Lobster', 'protein', 'seafood'),
('Squid', 'protein', 'seafood'),
('Oyster', 'protein', 'seafood'),
('Clam', 'protein', 'seafood'),
('Prawn', 'protein', 'seafood'),
('Shrimp', 'protein', 'seafood'),
('Salmon', 'protein', 'seafood'),
('Tilapia', 'protein', 'seafood'),
('Tuna', 'protein', 'seafood'),
('Halibut', 'protein', 'seafood'),
('Bass', 'protein', 'seafood'),
('Snapper', 'protein', 'seafood'),
('Trout', 'protein', 'seafood'),
('Cod', 'protein', 'seafood'),
('Smoked salmon', 'protein', 'seafood'),
('Sole', 'protein', 'seafood'),
('Caviar', 'protein', 'seafood'),

-- protein vegetarian
('Button mushrooms', 'protein', 'vegetarian'),
('Portobello mushrooms', 'protein', 'vegetarian'),
('Shiitake mushrooms', 'protein', 'vegetarian'),
('Procini mushrooms', 'protein', 'vegetarian'),
('Wild mushrooms', 'protein', 'vegetarian'),
('Enoki mushrooms', 'protein', 'vegetarian'),
('Oyster mushrooms', 'protein', 'vegetarian'),
('Chanterelle mushrooms', 'protein', 'vegetarian'),
('Morel mushrooms', 'protein', 'vegetarian'),
('Lions mane mushrooms', 'protein', 'vegetarian'),
('Crimini mushrooms', 'protein', 'vegetarian'),
('Maitake mushrooms', 'protein', 'vegetarian'),
('Porcini mushrooms', 'protein', 'vegetarian'),
('Hedgehog mushrooms', 'protein', 'vegetarian'),
('Beech mushrooms', 'protein', 'vegetarian'),
('King trumpet mushrooms', 'protein', 'vegetarian'),
('Walnuts', 'protein', 'vegetarian'),
('Peanuts', 'protein', 'vegetarian'),
('Almonds', 'protein', 'vegetarian'),
('Sesame seeds', 'protein', 'vegetarian'),
('Cashews', 'protein', 'vegetarian'),
('Pine nuts', 'protein', 'vegetarian'),
('Pistachios', 'protein', 'vegetarian'),
('Chia seeds', 'protein', 'vegetarian'),
('Flax seeds', 'protein', 'vegetarian'),
('Peas', 'protein', 'vegetarian'),
('Green beans', 'protein', 'vegetarian'),
('Tofu', 'protein', 'vegetarian'),

-- Category: vegetables subcategory: roots_and_bulbs
('Bell pepper', 'vegetables', 'roots_and_bulbs'),
('Onion', 'vegetables', 'roots_and_bulbs'),
('Garlic', 'vegetables', 'roots_and_bulbs'),
('Carrot', 'vegetables', 'roots_and_bulbs'),
('Scallion', 'vegetables', 'roots_and_bulbs'),
('Red onion', 'vegetables', 'roots_and_bulbs'),
('Shallot', 'vegetables', 'roots_and_bulbs'),
('Sweet potato', 'vegetables', 'roots_and_bulbs'),
('Yukon gold potato', 'vegetables', 'roots_and_bulbs'),
('Russet potato', 'vegetables', 'roots_and_bulbs'),
('Purple potato', 'vegetables', 'roots_and_bulbs'),
('Fingerling potato', 'vegetables', 'roots_and_bulbs'),
('Jerusalem artichoke', 'vegetables', 'roots_and_bulbs'),
('Taro root', 'vegetables', 'roots_and_bulbs'),
 
-- Category: vegetables Subcategory: legumes
('Chickpeas', 'vegetables', 'legumes'),
('Black beans', 'vegetables', 'legumes'),
('Kidney beans', 'vegetables', 'legumes'),
('White beans', 'vegetables', 'legumes'),
('Pinto beans', 'vegetables', 'legumes'),
('Lentils', 'vegetables', 'legumes'),
('Snap peas', 'vegetables', 'legumes'),
('Bean sprouts', 'vegetables', 'legumes'),
('Cannellini beans', 'vegetables', 'legumes'),
('Garbanzo beans', 'vegetables', 'legumes'),
('Navy beans', 'vegetables', 'legumes'),
('Split peas', 'vegetables', 'legumes'),
('Black-eyed peas', 'vegetables', 'legumes'),
('Adzuki beans', 'vegetables', 'legumes'),
('Fava beans', 'vegetables', 'legumes'),
('Mung beans', 'vegetables', 'legumes'),
('Soybeans', 'vegetables', 'legumes'),
('Edamame', 'vegetables', 'legumes'),
 
  --  Category: vegetables Subcategory: cabbages
('Broccoli', 'vegetables', 'cabbages'),
('Cauliflower', 'vegetables', 'cabbages'),
('Cabbage', 'vegetables', 'cabbages'),
('Asparagus', 'vegetables', 'cabbages'),
('Kale', 'vegetables', 'cabbages'),
('Brussels sprouts', 'vegetables', 'cabbages'),
('Bok choy', 'vegetables', 'cabbages'),
('Savoy cabbage', 'vegetables', 'cabbages'),
('Red cabbage', 'vegetables', 'cabbages'),
('Napa cabbage', 'vegetables', 'cabbages'),
('Collard greens', 'vegetables', 'cabbages'),
('Mustard greens', 'vegetables', 'cabbages'),
('Turnip greens', 'vegetables', 'cabbages'),
('Swiss chard', 'vegetables', 'cabbages'),
('Spinach', 'vegetables', 'cabbages'),
('Arugula', 'vegetables', 'cabbages'),
('Watercress', 'vegetables', 'cabbages'),
 
-- Category: vegetables subcategory: fruit_vegetables
('Tomatoes', 'vegetables', 'fruit_vegetables'),
('Cucumber', 'vegetables', 'fruit_vegetables'),
('Sweet corn', 'vegetables', 'fruit_vegetables'),
('Eggplant', 'vegetables', 'fruit_vegetables'),
('Sun-dried tomato', 'vegetables', 'fruit_vegetables'),
('Green olives', 'vegetables', 'fruit_vegetables'),
('Black olives', 'vegetables', 'fruit_vegetables'),
('Pickles', 'vegetables', 'fruit_vegetables'),
('Bell peppers', 'vegetables', 'fruit_vegetables'),
('Jalapeno peppers', 'vegetables', 'fruit_vegetables'),
('Chili peppers', 'vegetables', 'fruit_vegetables'),
('Paprika', 'vegetables', 'fruit_vegetables'),
('Tomatillos', 'vegetables', 'fruit_vegetables'),
('Cayenne pepper', 'vegetables', 'fruit_vegetables'),
('Tabasco peppers', 'vegetables', 'fruit_vegetables'),
('Cherry tomatoes', 'vegetables', 'fruit_vegetables'),

  -- Category: fruits subcategory: common_fruits
('Apple', 'fruits', 'common_fruits'),
('Banana', 'fruits', 'common_fruits'),
('Pear', 'fruits', 'common_fruits'),
('Kiwi', 'fruits', 'common_fruits'),
('Plum', 'fruits', 'common_fruits'),
('Peach', 'fruits', 'common_fruits'),
('Nectarine', 'fruits', 'common_fruits'),
('Apricot', 'fruits', 'common_fruits'),
('Grape', 'fruits', 'common_fruits'),
('Pineapple', 'fruits', 'common_fruits'),
('Strawberry', 'fruits', 'common_fruits'),
('Raspberry', 'fruits', 'common_fruits'),
('Blueberry', 'fruits', 'common_fruits'),
('Blackberry', 'fruits', 'common_fruits'),
('Cranberry', 'fruits', 'common_fruits'),
('Cherry', 'fruits', 'common_fruits'),
('Frozen berry mix', 'fruits', 'common_fruits'),

--  ************** Category: fruits subcategory: citrus_tropical
('Lemon', 'fruits', 'citrus_tropical'),
('Lime', 'fruits', 'citrus_tropical'),
('Orange', 'fruits', 'citrus_tropical'),
('Grapefruit', 'fruits', 'citrus_tropical'),
('Tangerine', 'fruits', 'citrus_tropical'),
('Clementine', 'fruits', 'citrus_tropical'),
('Mango', 'fruits', 'citrus_tropical'),
('Pineapple', 'fruits', 'citrus_tropical'),
('Papaya', 'fruits', 'citrus_tropical'),
('Guava', 'fruits', 'citrus_tropical'),
('Passion fruits', 'fruits', 'citrus_tropical'),
('Kiwano (horned melon)', 'fruits', 'citrus_tropical'),
('Watermelon', 'fruits', 'citrus_tropical'),
('Cantaloupe', 'fruits', 'citrus_tropical'),
('Honeydew', 'fruits', 'citrus_tropical'),
('Galia melon', 'fruits', 'citrus_tropical'),
('Charentais melon', 'fruits', 'citrus_tropical'),

  -- Category: dairy subcategory: milk_and_cream
('Milk', 'dairy', 'milk_and_cream'),
('Non-fat milk', 'dairy', 'milk_and_cream'),
('2% milk', 'dairy', 'milk_and_cream'),
('Whole milk', 'dairy', 'milk_and_cream'),
('Half and half', 'dairy', 'milk_and_cream'),
('Heavy cream', 'dairy', 'milk_and_cream'),
('Butter', 'dairy', 'milk_and_cream'),
('Cream', 'dairy', 'milk_and_cream'),
('Whipped cream', 'dairy', 'milk_and_cream'),
('Condensed milk', 'dairy', 'milk_and_cream'),
('Evaporated milk', 'dairy', 'milk_and_cream'),
('Chocolate milk', 'dairy', 'milk_and_cream'),
('Milk powder', 'dairy', 'milk_and_cream'),
('Ice cream', 'dairy', 'milk_and_cream'),
('Buttermilk', 'dairy', 'milk_and_cream'),

  --  ************** Category: dairy subcategory: butters_and_yogurts
('Ghee', 'dairy', 'butters_and_yogurts'),
('Margarine', 'dairy', 'butters_and_yogurts'),
('Whipped butter', 'dairy', 'butters_and_yogurts'),
('Margarine spread', 'dairy', 'butters_and_yogurts'),
('Unsalted butter', 'dairy', 'butters_and_yogurts'),
('Salted butter', 'dairy', 'butters_and_yogurts'),
('European-style butter', 'dairy', 'butters_and_yogurts'),
('Yogurt', 'dairy', 'butters_and_yogurts'),
('Greek yogurt', 'dairy', 'butters_and_yogurts'),
('Low-fat yogurt', 'dairy', 'butters_and_yogurts'),
('Non-fat yogurt', 'dairy', 'butters_and_yogurts'),
('Organic yogurt', 'dairy', 'butters_and_yogurts'),
('Plant-based yogurt', 'dairy', 'butters_and_yogurts'),
('Coconut yogurt', 'dairy', 'butters_and_yogurts'),
('Almond yogurt', 'dairy', 'butters_and_yogurts'),
('Soy yogurt', 'dairy', 'butters_and_yogurts'),
('Icelandic yogurt', 'dairy', 'butters_and_yogurts'),
('Bulgarian yogurt', 'dairy', 'butters_and_yogurts'),
('Australian-style yogurt', 'dairy', 'butters_and_yogurts'),
('Drinkable yogurt', 'dairy', 'butters_and_yogurts'),
('Frozen yogurt', 'dairy', 'butters_and_yogurts'),

  -- Category: dairy subcategory: cheeses
('Feta', 'dairy', 'cheeses'),
('Mozzarella', 'dairy', 'cheeses'),
('Cheddar', 'dairy', 'cheeses'),
('Cream cheese', 'dairy', 'cheeses'),
('Parmesan', 'dairy', 'cheeses'),
('Ricotta', 'dairy', 'cheeses'),
('Blue cheese', 'dairy', 'cheeses'),
('Goat cheese', 'dairy', 'cheeses'),
('Cheese spread', 'dairy', 'cheeses'),
('Brie', 'dairy', 'cheeses'),
('Swiss cheese', 'dairy', 'cheeses'),
('Pepper jack cheese', 'dairy', 'cheeses'),
('Provolone', 'dairy', 'cheeses'),
('Colby cheese', 'dairy', 'cheeses'),
('Muenster cheese', 'dairy', 'cheeses'),
('Gouda', 'dairy', 'cheeses'),
('Havarti', 'dairy', 'cheeses'),
('Monterey Jack cheese', 'dairy', 'cheeses'),
('Queso fresco', 'dairy', 'cheeses'),
('Cotija cheese', 'dairy', 'cheeses'),
('Romano cheese', 'dairy', 'cheeses'),
('Asiago cheese', 'dairy', 'cheeses'),
('Gorgonzola', 'dairy', 'cheeses'),
('Sour cream', 'dairy', 'cheeses'),
('Cottage cheese', 'dairy', 'cheeses'),
('Roquefort', 'dairy', 'cheeses'),

  -- Category: dairy subcategory: lactose_free
('Lactose free milk', 'dairy', 'lactose_free'),
('Lactose free yogurt', 'dairy', 'lactose_free')
('Soy milk', 'dairy', 'lactose_free'),
('Almond milk', 'dairy', 'lactose_free'),
('Oat milk', 'dairy', 'lactose_free'),
('Cashew milk', 'dairy', 'lactose_free'),
('Coconut milk', 'dairy', 'lactose_free'),
('Hazelnut milk', 'dairy', 'lactose_free'),
('Rice milk', 'dairy', 'lactose_free'),
('Creamer (non-dairy)', 'dairy', 'lactose_free'),

  -- *********  Category: spice_and_condiments subcategory: oils
('Olive oil', 'spice_and_condiments', 'oils'),
('Canola oil', 'spice_and_condiments', 'oils'),
('Coconut oil', 'spice_and_condiments', 'oils'),
('Peanut oil', 'spice_and_condiments', 'oils'),
('Sesame oil', 'spice_and_condiments', 'oils'),
('Sunflower oil', 'spice_and_condiments', 'oils'),
('Safflower oil', 'spice_and_condiments', 'oils'),
('Avocado oil', 'spice_and_condiments', 'oils'),
('Grapeseed oil', 'spice_and_condiments', 'oils'),
('Corn oil', 'spice_and_condiments', 'oils'),
('Walnut oil', 'spice_and_condiments', 'oils'),
('Flaxseed oil', 'spice_and_condiments', 'oils'),
('Hempseed oil', 'spice_and_condiments', 'oils'),
('Almond oil', 'spice_and_condiments', 'oils'),
('Hazelnut oil', 'spice_and_condiments', 'oils'),
('Palm oil', 'spice_and_condiments', 'oils'),
('Soybean oil', 'spice_and_condiments', 'oils'),
('Rice bran oil', 'spice_and_condiments', 'oils'),
('Camelina oil', 'spice_and_condiments', 'oils'),

  -- Category: spice_and_condiments subcategory spices
('Pepper', 'spice_and_condiments', 'spices'),
('Chili flake', 'spice_and_condiments', 'spices'),
('Chili powder', 'spice_and_condiments', 'spices'),
('Paprika', 'spice_and_condiments', 'spices'),
('Cayenne', 'spice_and_condiments', 'spices'),
('Nutmeg', 'spice_and_condiments', 'spices'),
('Turmeric', 'spice_and_condiments', 'spices'),
('Clove', 'spice_and_condiments', 'spices'),
('Chile pepper', 'spice_and_condiments', 'spices'),
('Cardamom', 'spice_and_condiments', 'spices'),
('Peppercorn', 'spice_and_condiments', 'spices'),
('Fennel seed', 'spice_and_condiments', 'spices'),
('Chipotle', 'spice_and_condiments', 'spices'),
('Cumin', 'spice_and_condiments', 'spices'),
('Ginger', 'spice_and_condiments', 'spices'),
('Horseradish', 'spice_and_condiments', 'spices'),
('Wasabi', 'spice_and_condiments', 'spices'),
('Szechuan peppercorns', 'spice_and_condiments', 'spices'),
('Aleppo pepper', 'spice_and_condiments', 'spices'),
('Bird eye chili', 'spice_and_condiments', 'spices'),
('Habanero pepper', 'spice_and_condiments', 'spices'),
('Scotch bonnet pepper', 'spice_and_condiments', 'spices'),

  -- Category: spice_and_condiments subcategory: aromatics
('Garlic', 'spice_and_condiments', 'aromatics'),
('Onion', 'spice_and_condiments', 'aromatics'),
('Ginger', 'spice_and_condiments', 'aromatics'),
('Lemongrass', 'spice_and_condiments', 'aromatics'),
('Shallots', 'spice_and_condiments', 'aromatics'),
('Scallions', 'spice_and_condiments', 'aromatics'),
('Chives', 'spice_and_condiments', 'aromatics'),
('Cilantro', 'spice_and_condiments', 'aromatics'),
('Parsley', 'spice_and_condiments', 'aromatics'),
('Thyme', 'spice_and_condiments', 'aromatics'),
('Rosemary', 'spice_and_condiments', 'aromatics'),
('Sage', 'spice_and_condiments', 'aromatics'),
('Bay leaves', 'spice_and_condiments', 'aromatics'),
('Basil', 'spice_and_condiments', 'aromatics'),
('Mint', 'spice_and_condiments', 'aromatics'),
('Oregano', 'spice_and_condiments', 'aromatics'),
('Dill', 'spice_and_condiments', 'aromatics'),

  -- Category: spice_and_condiments subcategory: baking_essentials
('Flour', 'spice_and_condiments', 'baking_essentials'),
('Sugar', 'spice_and_condiments', 'baking_essentials'),
('Icing Sugar', 'spice_and_condiments', 'baking_essentials'),
('Vanilla extract', 'spice_and_condiments', 'baking_essentials'),
('Baking powder', 'spice_and_condiments', 'baking_essentials'),
('Baking soda', 'spice_and_condiments', 'baking_essentials'),
('Yeast', 'spice_and_condiments', 'baking_essentials'),
('Chocolate chips', 'spice_and_condiments', 'baking_essentials'),
('Gelatin', 'spice_and_condiments', 'baking_essentials'),
('Cornmeal', 'spice_and_condiments', 'baking_essentials'),
('Panko', 'spice_and_condiments', 'baking_essentials'),
('Cornstarch', 'spice_and_condiments', 'baking_essentials'),

  -- Category: spice_and_condiments subcategory: condiments
('Worcestershire sauce', 'spice_and_condiments', 'condiments'),
('Vinegar', 'spice_and_condiments', 'condiments'),
('Malt Vinegar', 'spice_and_condiments', 'condiments'),
('Soy sauce', 'spice_and_condiments', 'condiments'),
('Mustard', 'spice_and_condiments', 'condiments'),
('Ketchup', 'spice_and_condiments', 'condiments'),
('Mayonnaise', 'spice_and_condiments', 'condiments'),
('Relish', 'spice_and_condiments', 'condiments'),
('BBQ sauce', 'spice_and_condiments', 'condiments'),
('Teriyaki sauce', 'spice_and_condiments', 'condiments'),
('Hoisin sauce', 'spice_and_condiments', 'condiments'),
('Fish sauce', 'spice_and_condiments', 'condiments'),
('Pickles', 'spice_and_condiments', 'condiments'),
('Olives', 'spice_and_condiments', 'condiments'),
('Capers', 'spice_and_condiments', 'condiments'),
('Anchovy paste', 'spice_and_condiments', 'condiments'),
('Tomato paste', 'spice_and_condiments', 'condiments'),
('Tahini', 'spice_and_condiments', 'condiments'),
('Honey', 'spice_and_condiments', 'condiments'),
('Maple syrup', 'spice_and_condiments', 'condiments'),
('Molasses', 'spice_and_condiments', 'condiments'),
('Agave nectar', 'spice_and_condiments', 'condiments'),

  -- Category: pice_and_condiments subcategory: spice_blends
('Curry powder', 'spice_and_condiments', 'spice_blends'),
('Chinese five spice', 'spice_and_condiments', 'spice_blends'),
('Ras el hanout', 'spice_and_condiments', 'spice_blends'),
('Za''atar', 'spice_and_condiments', 'spice_blends'),
('Harissa', 'spice_and_condiments', 'spice_blends'),
('Berbere', 'spice_and_condiments', 'spice_blends'),
('Adobo', 'spice_and_condiments', 'spice_blends'),
('Jerk seasoning', 'spice_and_condiments', 'spice_blends'),
('Baharat', 'spice_and_condiments', 'spice_blends'),
('Tandoori masala', 'spice_and_condiments', 'spice_blends'),
('Herbes de Provence', 'spice_and_condiments', 'spice_blends'),
('Fines herbs', 'spice_and_condiments', 'spice_blends'),
('Bouquet garni', 'spice_and_condiments', 'spice_blends'),
('Old Bay seasoning', 'spice_and_condiments', 'spice_blends'),
('poultry seasoning', 'spice_and_condiments', 'spice_blends'),
('Pumpkin pie spice', 'spice_and_condiments', 'spice_blends'),
('Steak seasoning', 'spice_and_condiments', 'spice_blends'),
('Chili seasoning', 'spice_and_condiments', 'spice_blends'),
('Fajita seasoning', 'spice_and_condiments', 'spice_blends'),
('Ranch seasoning', 'spice_and_condiments', 'spice_blends'),
('Cajun seasoning', 'spice_and_condiments', 'spice_blends'),

  -- Category: alcohol subcategory: beer_spirits_and_wines
('Beer', 'alcohol', 'beer_spirits_and_wines'),
('Rum', 'alcohol', 'beer_spirits_and_wines'),
('Cider', 'alcohol', 'beer_spirits_and_wines'),
('Bourbon', 'alcohol', 'beer_spirits_and_wines'),
('Tequila', 'alcohol', 'beer_spirits_and_wines'),
('Sherry', 'alcohol', 'beer_spirits_and_wines'),
('Bitters', 'alcohol', 'beer_spirits_and_wines'),
('Sake', 'alcohol', 'beer_spirits_and_wines'),
('White wine', 'alcohol', 'beer_spirits_and_wines'),
('Red wine', 'alcohol', 'beer_spirits_and_wines'),
('Rice wine', 'alcohol', 'beer_spirits_and_wines'),
('Port wine', 'alcohol', 'beer_spirits_and_wines'),
('Rose wine', 'alcohol', 'beer_spirits_and_wines');